# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: ethanhxu@gmail.com
author_name: Ethan Xu
contract_name: news_verification
deployment_language: python
preset_name: starter
project_name: News-Verification

